@startuml
class Livre{
}
interface Utilisateur{
    Nom
    Prenom
    MotDePasse
}

enum Role{
    Adherent,
    Admin
}
Utilisateur --> "1 role" Role
Utilisateur "0..1 adherent"- "0..*\n livres" Livre : " "

class Emprunt{
    DateEmprunt
    DateRetour
}

(Utilisateur, Livre) .. Emprunt
class Controleur
Controleur - "0..* livres" Livre
Controleur -- "0..*\nutilisateurs" Utilisateur: " "
Controleur ---- "0..*\nemprunts" Emprunt: "   "

@enduml