@startuml
'idea.partialRender
(Login) .> Adherent : <<includes>>
(Login) .> Admin : <<includes>>
Adherent -(Emprunte un livre)
Adherent -- (Rendre un livre)
Adherent --- (Chercher un livre)
(Chercher un livre) .> (Emprunte un livre) : <<extends>>
Admin - (Lister les adhérents)
Admin -- (Créer un nouvel adhérent)
Admin -- (Supprimer un adhérent)
Admin --- (Lister les emprunts)
Admin --- (Ajouter un nouvel emprunt)
Admin --- (Ajouter un nouveau livre)
Admin --- (Supprimer un livre)
Admin --|> Adherent


@enduml